Lesson 4, level5,Task_16
antdolg1/jg_java_1_wednesday_september_2022 pull request #134
Opened 2022-10-23 18:10 UTC by IljaMorozovs

add light detector program
add new method detect to LightColorDetector
add test for method detect in LightColorDetectorTest

2022-11-27 13:31 UTC, antdolg1 commented on src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_5/Task_16/LightColorDetector.java
> +        String lightColor = null;
Не надо создавать строку со значением null, это может привести к потенциальному NullPointerException. Если тебе надо создать пустую строку, то делай это так:
`String lightColor = "";`

2022-11-27 13:32 UTC, antdolg1 requested changes
Нужно небольшая правка, глянь мой комментарий.

2022-11-29 11:33 UTC, IljaMorozovs commented on src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_5/Task_16/LightColorDetector.java
> +        String lightColor = null;
убрал Null

2022-12-06 19:39 UTC, antdolg1 approved these changes

2022-12-06 19:39 UTC, merged