homework level2 Task5,6,7
antdolg1/jg_java_1_wednesday_september_2022 pull request #148
Opened 2022-10-25 17:47 UTC by aMADsss

2022-11-21 15:13 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_4/homework/level_2/Task_6/LargestNumbers.java
> +public class LargestNumbers {
Неправильно название класса. В шестом задании нужно найти наименьшее число из двух. Исправь название класса.

2022-11-21 15:14 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_4/homework/level_2/Task_7/LargestNumbers.java
> +public class LargestNumbers {
Неправильно название класса. В седьмом задании нужно понять равные ли числа.

2022-11-21 15:14 UTC, antdolg1 requested changes
Есть недочёты, посмотри мои комментарии.

2022-11-23 12:59 UTC, aMADsss commented on src/main/java/students/student_aleksandrs_mads/lesson_4/homework/level_2/Task_6/LargestNumbers.java
> +public class LargestNumbers {
rename class name

2022-11-23 13:00 UTC, aMADsss commented on src/main/java/students/student_aleksandrs_mads/lesson_4/homework/level_2/Task_7/LargestNumbers.java
> +public class LargestNumbers {
rename class name

2022-11-27 13:49 UTC, antdolg1 approved these changes

2022-11-27 13:49 UTC, merged