St igor budnitski lesson2 level3
antdolg1/jg_java_1_wednesday_september_2022 pull request #20
Opened 2022-10-07 12:42 UTC by igor-budnitski

Lesson2 - level3 homework

2022-10-11 19:42 UTC, antdolg1 commented on src/main/java/students/student_igor_budnitski/level3/Task9.java
> +        for (int i = 1; i < 10; i++) {
Этот цикл выведит на консоль результат умножения до 9.

2022-10-11 19:43 UTC, antdolg1 requested changes
Нужно исправить недочёт в 9ом задании.

2022-10-12 04:34 UTC, igor-budnitski commented
Code was updated and changed cycle to 10

2022-10-15 16:23 UTC, antdolg1 approved these changes
Good job!

2022-10-15 16:23 UTC, merged