St svetlana seda lesson 4
antdolg1/jg_java_1_wednesday_september_2022 pull request #219
Opened 2022-11-05 11:30 UTC by java0711

finally, checks passed :)

2023-01-16 18:38 UTC, antdolg1 commented on src/main/java/students/student_svetlana_seda/lesson_4/homework/level_3/TheBiggest.java
> +        if ((number1 > number2) && (number1 > number3)) {
Не обязательно обворачивать каждое условие в отдельные скобки.

2023-01-16 18:39 UTC, antdolg1 commented on src/main/java/students/student_svetlana_seda/lesson_4/homework/level_4/Calculator.java
> +        } else if (secondNumber > firstNumber) {
Это условия тут лишнее, так как у тебя только два возможных варианта, поэтому вторая проверка не нужна и её можно убрать.

2023-01-16 18:39 UTC, antdolg1 commented on src/main/java/students/student_svetlana_seda/lesson_4/homework/level_4/Calculator.java
> +//идея предложила, чтобы исправить ошибку добавить это:
Да, всё верно, так как твой метод должен возвращать какой-то int.  Вот если бы твой метод был void, тогда ничего возвращать не недо было.

2023-01-16 18:41 UTC, antdolg1 commented on src/main/java/students/student_svetlana_seda/lesson_4/homework/level_5/LightColorDetectorTest.java
> +        lightColorDetectorTest = new LightColorDetectorTest();
Эту строчку можно удалить, ты на 7ой строчке уже создала объект типа LightColorDetectorTest.

2023-01-16 18:41 UTC, antdolg1 commented on src/main/java/students/student_svetlana_seda/lesson_4/homework/level_5/LightColorDetectorTest.java
> +        // detectTest(); НАДО?
Да, надо.

2023-01-16 18:43 UTC, antdolg1 commented on src/main/java/students/student_svetlana_seda/lesson_4/homework/level_6/Stock.java
> +import java.sql.SQLOutput;
Лишний импорт, пожалуйста удали.

2023-01-16 18:44 UTC, antdolg1 requested changes
В целом неплохо, но требуются кое-какие исправления. Смотри мои комментарии.

2023-01-22 16:25 UTC, java0711 commented on src/main/java/students/student_svetlana_seda/lesson_4/homework/level_3/TheBiggest.java
> +        if ((number1 > number2) && (number1 > number3)) {
Done, thank you!

2023-01-22 16:40 UTC, java0711 commented on src/main/java/students/student_svetlana_seda/lesson_4/homework/level_4/Calculator.java
> +        } else if (secondNumber > firstNumber) {
corrected, ty!

2023-01-22 16:47 UTC, java0711 commented on src/main/java/students/student_svetlana_seda/lesson_4/homework/level_6/Stock.java
> +import java.sql.SQLOutput;
done, ty

2023-01-22 16:48 UTC, java0711 commented
All corrected, plz merge!

2023-01-23 18:37 UTC, antdolg1 approved these changes

2023-01-23 18:37 UTC, merged