St igor budnitski lesson2 level6
antdolg1/jg_java_1_wednesday_september_2022 pull request #29
Opened 2022-10-08 16:35 UTC by igor-budnitski

Lesson2-level6-homework

2022-10-15 20:20 UTC, antdolg1 commented on src/main/java/students/student_igor_budnitski/HelloWorld.java
> +import java.util.Scanner;
Remove unused import.

2022-10-15 20:20 UTC, antdolg1 requested changes
Changes needed.

2022-10-18 05:12 UTC, igor-budnitski commented on src/main/java/students/student_igor_budnitski/HelloWorld.java
> +import java.util.Scanner;
Removed

2022-10-19 19:24 UTC, antdolg1 approved these changes

2022-10-19 19:24 UTC, merged