Lesson 2 Level 3 done
antdolg1/jg_java_1_wednesday_september_2022 pull request #36
Opened 2022-10-09 17:39 UTC by kskaretnikov

2022-10-15 20:13 UTC, antdolg1 commented on src/main/java/students/student_konstantin_karetnikov/AveArithm.java
> +    }
Format code and remove redundant empty lines.

2022-10-15 20:14 UTC, antdolg1 commented on src/main/java/students/student_konstantin_karetnikov/MltplTable.java
> +    }
Same here, format and remove empty lines.

2022-10-15 20:14 UTC, antdolg1 commented on src/main/java/students/student_konstantin_karetnikov/PerimeterArea.java
> +        double Number;
Variable name cannot start from capital letter.

Also format code and remove empty lines.

2022-10-15 20:15 UTC, antdolg1 requested changes
Changes needed.

2022-10-16 13:54 UTC, kskaretnikov commented
Changed

2022-10-19 19:21 UTC, antdolg1 approved these changes

2022-10-19 19:21 UTC, merged