Lesson 2 Level 5 done
antdolg1/jg_java_1_wednesday_september_2022 pull request #37
Opened 2022-10-09 17:40 UTC by kskaretnikov

2022-10-15 20:26 UTC, antdolg1 commented on src/main/java/students/student_konstantin_karetnikov/NoLineChange.java
> +    private static java.lang.String String;
Remove path to library.

2022-10-15 20:27 UTC, antdolg1 requested changes
Changes needed.

2022-10-16 14:23 UTC, kskaretnikov commented
Changed

2022-10-19 19:20 UTC, antdolg1 approved these changes

2022-10-19 19:20 UTC, merged