Lesson 2 Level 7 done
antdolg1/jg_java_1_wednesday_september_2022 pull request #39
Opened 2022-10-09 17:42 UTC by kskaretnikov

2022-10-15 20:29 UTC, antdolg1 commented on src/main/java/students/student_konstantin_karetnikov/Homework/Hello_World.java
>  public class Hello_World {public static void main(String[] args) {System.out.println("Hello World!");
Format code.

2022-10-15 20:30 UTC, antdolg1 requested changes
Format code.

2022-10-16 14:27 UTC, kskaretnikov commented
formated

2022-10-19 19:19 UTC, antdolg1 commented on src/main/java/students/student_konstantin_karetnikov/Homework/Hello_World.java
>  public class Hello_World {public static void main(String[] args) {System.out.println("Hello World!");
Apply format lines Ctrl+Alt+L

2022-10-30 20:00 UTC, antdolg1 commented on src/main/java/students/student_konstantin_karetnikov/Homework/HelloWorld.java
> +}
Still not formatted. Formatted code should look like this:

```
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
```

2022-11-08 20:08 UTC, antdolg1 approved these changes

2022-11-08 20:08 UTC, merged