homework lesson2 level1
antdolg1/jg_java_1_wednesday_september_2022 pull request #46
Opened 2022-10-10 12:23 UTC by aMADsss

add task1 and task2

2022-10-10 13:09 UTC, IljaMorozovs requested changes

2022-10-10 13:09 UTC, IljaMorozovs commented on src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_1/Task_1.java
> +        Scanner scanner=new Scanner(System.in);
Please reformat all code Ctrl+Alt+L

2022-10-15 20:45 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_1/Task_1.java
> +        Scanner scanner=new Scanner(System.in);
Surround assignment operator with spaces here and in all other places. Also add missing spaces aroung `+ - / *`

2022-10-15 20:45 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_1/Task_2.java
> +        double summ = firstDoubleNumber + secondDoubleNumber;
summ -> sum

2022-10-15 20:46 UTC, antdolg1 requested changes
Changes needed.

2022-10-19 19:17 UTC, merged