St igor budnitski lesson2 level8
antdolg1/jg_java_1_wednesday_september_2022 pull request #53
Opened 2022-10-11 08:28 UTC by igor-budnitski

Lesson2 - level8 -homework
Smart calculator, where user can enter numbers and select required operation

2022-10-15 20:55 UTC, antdolg1 commented on src/main/java/students/student_igor_budnitski/HelloWorld.java
> +import java.util.Scanner;
Unused import. Please remove.

2022-10-15 20:55 UTC, antdolg1 commented on src/main/java/students/student_igor_budnitski/level8/Calculator.java
> +
Redundant empty line.

2022-10-15 21:01 UTC, antdolg1 requested changes
Changes needed.

2022-10-18 05:09 UTC, igor-budnitski commented on src/main/java/students/student_igor_budnitski/level8/Calculator.java
> +
Changes were applied and empty line was removed.

2022-10-19 19:25 UTC, antdolg1 approved these changes

2022-10-19 19:26 UTC, merged