St svetlana seda lesson2 level1
antdolg1/jg_java_1_wednesday_september_2022 pull request #56
Opened 2022-10-11 17:22 UTC by java0711

Не понимаю или добавила правильноБ не могу найти класс у себя. Проверка

2022-10-15 18:24 UTC, antdolg1 commented on src/main/java/students/student_svetlana_seda/lesson_2/level_1/Task1.java
> +        Scanner scanner=new Scanner(System.in);
Please add spaces before and after assignment operator (here and in other places).

2022-10-15 18:25 UTC, antdolg1 requested changes
Please add spaces where required.

2022-10-17 16:20 UTC, java0711 commented on src/main/java/students/student_svetlana_seda/lesson_2/level_1/Task1.java
> +        Scanner scanner=new Scanner(System.in);
Sorry, I did not understand, space between line 8 and 9?

2022-10-17 16:23 UTC, java0711 commented on src/main/java/students/student_svetlana_seda/lesson_2/level_1/Task1.java
> +        Scanner scanner=new Scanner(System.in);
or: 
Scanner scanner = new Scanner(System.in);

2022-10-19 19:26 UTC, antdolg1 commented on src/main/java/students/student_svetlana_seda/lesson_2/level_1/Task1.java
> +        Scanner scanner=new Scanner(System.in);
`Scanner scanner=new Scanner(System.in);` -> `Scanner scanner = new Scanner(System.in);`

2022-10-19 19:26 UTC, antdolg1 approved these changes

2022-10-19 19:26 UTC, merged