st ignat parfenov lesson2 level1
antdolg1/jg_java_1_wednesday_september_2022 pull request #6
Opened 2022-10-05 19:06 UTC by joseip08

2022-10-11 18:17 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson2_hw_level_1_intern/ScannerMethod.java
> +}
Не хватает форматирования. Как автоматически отформатировать код: https://www.jetbrains.com/idea/guide/tips/reformat-file/

2022-10-11 18:18 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson2_hw_level_1_intern/ScannerMethod.java
> +    System.out.println("Addition result is : " + (firstNumber+secondNumber));
`firstNumber+secondNumber` -> `firstNumber + secondNumber`

Так легче читать и воспринимать код. Исправь в остальных местах тоже.

2022-10-11 18:19 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson2_hw_level_1_intern/Task1_ScannerMethod_Int.java
> +        System.out.println("Subtraction result is : " + (firstNumber-secondNumber));
`
firstNumber+secondNumber` -> `firstNumber + secondNumber`

Так легче читать и воспринимать код. Исправь в остальных местах тоже.

2022-10-11 18:20 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson2_hw_level_1_intern/Task2_ScannerMethod_Double.java
> +        System.out.println("The subtraction result is : " +(firstNumber-secondNumber-thirdNumber));
`
firstNumber+secondNumber+thirdNumber` -> `firstNumber + secondNumber + thirdNumber`

Так легче читать и воспринимать код. Исправь в остальных местах тоже.

2022-10-11 18:25 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson2_hw_level_1_intern/Task1_ScannerMethod_Int.java
> +public class Task1_ScannerMethod_Int {
Избегай нижних подчёркиваний в названиях классов.

2022-10-11 18:26 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson2_hw_level_1_intern/Task2_ScannerMethod_Double.java
> +public class Task2_ScannerMethod_Double {
Избегай нижних подчёркиваний в названиях классов.

2022-10-11 18:28 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson2_hw_level_3_junior/Task9.java
> +
Не хватает форматирования + убери лишние пустые строки.

2022-10-11 18:32 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson2_hw_level_2_intern/Task3.java
> +}
Это не совсем то, что нужно в задании номер 3.

2022-10-11 18:33 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson2_hw_level_2_intern/Phone.java
> +    }
Не обязательно создавать main метод для решения этого задания.
Достаточно просто добавить необходимую скобку.

Задание:
```
class Phone

}
```

Решение:

```
class Phone {

}
```

2022-10-11 18:34 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/PrimeNumbers2.java
> +
Много лишних пустых строк.

2022-10-11 18:35 UTC, antdolg1 requested changes
Посмотри комментарии. Много где не хватает форматирования, где-то плохо подобраны называния, где-то нет пробелов и так далее. В основном ошибки стилистические.

2022-10-11 18:58 UTC, joseip08 commented
Спасибо!

Завтра посмотрю, исправлю👌

Спасибо
И.

Inviato da iPhone

> Il giorno 11 ott 2022, alle ore 21:36, Antons Dolgopolovs ***@***.***> ha scritto:
> 
> @antdolg1 requested changes on this pull request.
> 
> Посмотри комментарии. Много где не хватает форматирования, где-то плохо подобраны называния, где-то нет пробелов и так далее. В основном ошибки стилистические.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2022-10-15 16:09 UTC, antdolg1 approved these changes

2022-10-15 16:09 UTC, merged