St svetlana seda lesson2 level2
antdolg1/jg_java_1_wednesday_september_2022 pull request #65
Opened 2022-10-12 15:17 UTC by java0711

Please check my homework for level 2. TY

2022-10-15 21:36 UTC, antdolg1 commented on src/main/java/students/student_svetlana_seda/lesson_2/level_2/HelloLana.java
> +            String n;
Bad variable name, please fix.

Also format lines.

2022-10-15 21:37 UTC, antdolg1 requested changes
Fix naming.

2022-10-19 19:27 UTC, antdolg1 commented on src/main/java/students/student_svetlana_seda/lesson_2/level_2/HelloLana.java
> +            String n;
Use auto format: `Ctrl+Alt+L`

2022-10-19 19:28 UTC, antdolg1 requested changes
Apply autoformat on your code in class HelloLana.java

2022-10-20 15:27 UTC, java0711 commented on src/main/java/students/student_svetlana_seda/lesson_2/level_2/HelloLana.java
> +            String n;
Thanks, corrected now.

2022-10-20 15:28 UTC, java0711 commented
All corrected. Ty.

2022-10-24 15:09 UTC, java0711 commented
Please confirm what is wrong? What changes need to be done? Autoformat done and the name fixed... ty

2022-10-25 19:30 UTC, antdolg1 approved these changes

2022-10-25 19:31 UTC, antdolg1 approved these changes

2022-10-25 19:31 UTC, merged