St ilja morozovs lesson3 level7
antdolg1/jg_java_1_wednesday_september_2022 pull request #79
Opened 2022-10-16 12:52 UTC by IljaMorozovs

Completed level7

2022-10-25 20:02 UTC, antdolg1 commented on src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_29/PhoneBook.java
> +    }
Добавь пустую строку после каждого метода чтобы было легче читать код.

2022-10-25 20:04 UTC, IljaMorozovs commented on src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_29/PhoneBook.java
> +    }
Хорошо забыл 😃

2022-10-25 20:05 UTC, antdolg1 requested changes
Во всем коде добавь пробелы перед и после каждого оператора (*, /, =, + и так далее.)
Добавь пустые строки чтобы зрительно отделять переменные от методов и методы друг от друга.

2022-10-30 20:05 UTC, antdolg1 approved these changes

2022-10-30 20:05 UTC, merged