St ignat parfenov lesson3
antdolg1/jg_java_1_wednesday_september_2022 pull request #80
Opened 2022-10-16 15:52 UTC by joseip08

Hi Anton,
Could you check my lesson 3 HW (tasks1-12).
Thank you!

2022-10-25 20:07 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson3/BankAccount.java
> +        moneyAmount += + moneyToAdd;
Для чего второй плюс?

2022-10-25 20:08 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson3/homework/task11_13/Robot.java
> +
Лишняя пустая строка.

2022-10-25 20:08 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson3/homework/task11_13/Robot.java
> +
Лишняя пустая строка.

2022-10-25 20:08 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson3/homework/task11_13/RobotDemo.java
> +
Лишние пустые строки.

2022-10-25 20:09 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson3/homework/task11_13/RobotDemo.java
> +    }
Этот конструктор не нужен. Можно его убрать.

2022-10-25 20:11 UTC, antdolg1 requested changes
Есть кое-какие недочёты. Нужно исправить.

2022-10-26 15:50 UTC, joseip08 commented
Ок. Понял. Спасибо!
Всё исправлю

Спасибо
Игнат

> 25 окт. 2022 г., в 23:11, Antons Dolgopolovs ***@***.***> написал(а):
> 
> 
> @antdolg1 requested changes on this pull request.
> 
> Есть кое-какие недочёты. Нужно исправить.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/antdolg1/jg_java_1_wednesday_september_2022/pull/80#pullrequestreview-1155435319>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/A3KMZM6EXQCSNF4MBZCS6ULWFA5H7ANCNFSM6AAAAAARGM2BDA>.
> You are receiving this because you authored the thread.

2022-10-27 09:57 UTC, joseip08 commented
Антон привет!

Недочеты исправил. Пуш сделал:)
Будет время - посмотри пожалуйста

Хорошего дня
И.

> 25 окт. 2022 г., в 23:11, Antons Dolgopolovs ***@***.***> написал(а):
> 
> 
> @antdolg1 requested changes on this pull request.
> 
> Есть кое-какие недочёты. Нужно исправить.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/antdolg1/jg_java_1_wednesday_september_2022/pull/80#pullrequestreview-1155435319>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/A3KMZM6EXQCSNF4MBZCS6ULWFA5H7ANCNFSM6AAAAAARGM2BDA>.
> You are receiving this because you authored the thread.

2022-10-30 20:07 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson_5/lessoncode/ArraysApp.java
> +}
Почему код пятого урока оказался в ветке с домашками третьего урока? Исправь пожалуйста.

2022-10-30 20:08 UTC, antdolg1 commented on src/main/java/students/student_ignat_parfenov/lesson3/homework/task11_13/RobotDemo.java
> +    }
Пустой конструктор можно убрать, так как он нигде не используется.

2022-10-30 20:09 UTC, antdolg1 requested changes
Ещё пару моментов осталось. Убери ненужный пустой конструктор и файлы из пятого урока.

2022-10-31 17:24 UTC, joseip08 commented
Привет!

Да, все исправлю. Спасибо!

> 30 окт. 2022 г., в 22:09, Antons Dolgopolovs ***@***.***> написал(а):
> 
> 
> @antdolg1 requested changes on this pull request.
> 
> Ещё пару моментов осталось. Убери ненужный пустой конструктор и файлы из пятого урока.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/antdolg1/jg_java_1_wednesday_september_2022/pull/80#pullrequestreview-1161185874>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/A3KMZMYBWLHUFXAARQJCREDWF3BXBANCNFSM6AAAAAARGM2BDA>.
> You are receiving this because you authored the thread.

2022-10-31 18:36 UTC, joseip08 commented
Антон, добрый вечер!

Всё сделал.

Спасибо!

> 30 окт. 2022 г., в 22:09, Antons Dolgopolovs ***@***.***> написал(а):
> 
> 
> @antdolg1 requested changes on this pull request.
> 
> Ещё пару моментов осталось. Убери ненужный пустой конструктор и файлы из пятого урока.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/antdolg1/jg_java_1_wednesday_september_2022/pull/80#pullrequestreview-1161185874>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/A3KMZMYBWLHUFXAARQJCREDWF3BXBANCNFSM6AAAAAARGM2BDA>.
> You are receiving this because you authored the thread.

2022-11-21 10:00 UTC, antdolg1 approved these changes
Вот теперь всё хорошо. Так держать!

2022-11-21 10:00 UTC, merged