add lesson3 level1
antdolg1/jg_java_1_wednesday_september_2022 pull request #85
Opened 2022-10-17 14:59 UTC by aMADsss

2022-10-25 19:56 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_2/Robot.java
> +}
Не хватает форматирования.

2022-10-25 19:56 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_3/Robot.java
> +}
Не хватает форматирования.

2022-10-25 19:56 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_3/RobotDemo.java
> +}
Лишние пустые строчки + не хватает форматирования.

2022-10-25 19:56 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_4/Robot.java
> +}
Лишние пустые строчки + не хватает форматирования.

2022-10-25 19:56 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_4/RobotDemo.java
> +
Лишние пустые строчки + не хватает форматирования.

2022-10-25 19:56 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_5/Robot.java
> +}
Лишние пустые строчки + не хватает форматирования.

2022-10-25 19:56 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_5/RobotDemo.java
> +
Лишние пустые строчки + не хватает форматирования.

2022-10-25 19:56 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_6/Robot.java
> +}
Лишние пустые строчки + не хватает форматирования.

2022-10-25 19:56 UTC, antdolg1 commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_6/RobotDemo.java
> +
Лишние пустые строчки + не хватает форматирования.

2022-10-25 19:57 UTC, antdolg1 requested changes
Отформатируй код и убери лишние пустые строчки.

2022-10-27 08:29 UTC, aMADsss commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_2/Robot.java
> +}
formated

2022-10-27 08:31 UTC, aMADsss commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_3/RobotDemo.java
> +}
formated

2022-10-27 08:32 UTC, aMADsss commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_4/Robot.java
> +}
formated

2022-10-27 08:32 UTC, aMADsss commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_4/RobotDemo.java
> +
formated

2022-10-27 08:35 UTC, aMADsss commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_5/Robot.java
> +}
formated

2022-10-27 08:36 UTC, aMADsss commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_6/Robot.java
> +}
formated

2022-10-27 08:36 UTC, aMADsss commented on src/main/java/students/student_aleksandrs_mads/lesson_3/homework/Task_6/RobotDemo.java
> +
formated

2022-10-30 20:10 UTC, antdolg1 approved these changes

2022-10-30 20:10 UTC, merged